version: 2.1

jobs:
  build-and-test:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - checkout
      - run:
          name: Restore NuGet packages
          command: dotnet restore
      - run:
          name: Build solution
          command: dotnet build --no-restore --configuration Release
      - run:
          name: Run unit tests
          command: dotnet test --no-build --verbosity normal --configuration Release

workflows:
  build-and-test-workflow:
    jobs:
      - build-and-test
